### ISSUE TITLE
CalledProcessError from codesign during replace_signature()

### ISSUE THREAD

**Issue by SeanDS** [matthew-brett/delocate#144]
**Describe the bug**
I'm getting an error from `codesign` during the subprocess call in `replace_signature()` but can't see what it is:

```
subprocess.CalledProcessError: Command '['codesign', '--force', '--sign', '-', '/private/var/folders/kn/nxysct9107z1wgpvst2rr83r0000gt/T/tmpsm7lut6m/wheel/finesse/.dylibs/libklu.1.3.8.dylib']' returned non-zero exit status 106.
```

I'm running `delocate-wheel -vv` to get all verbose output, but since it's a subprocess it appears not to be emitted to stderr to let me try to diagnose the issue.

**To Reproduce**
Here's the full output from the GitLab CI job executed:

```
$ delocate-listdeps --all wheelhouse/*.whl
/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libamd.2.4.6.dylib
/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libbtf.1.2.6.dylib
/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libcolamd.2.9.6.dylib
/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libklu.1.3.8.dylib
/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libomp.dylib
/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libsuitesparseconfig.5.10.1.dylib
/usr/lib/libSystem.B.dylib
$ delocate-wheel -vv wheelhouse/*.whl
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Ignoring /usr/lib/libSystem.B.dylib and its dependencies.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libklu.1.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libklu.1.3.8.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libklu.1.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libklu.1.3.8.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libamd.2.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libamd.2.4.6.dylib
DEBUG:delocate.libsana:@rpath/libcolamd.2.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libcolamd.2.9.6.dylib
DEBUG:delocate.libsana:@rpath/libbtf.1.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libbtf.1.2.6.dylib
DEBUG:delocate.libsana:@rpath/libsuitesparseconfig.5.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libsuitesparseconfig.5.10.1.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libamd.2.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libamd.2.4.6.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libsuitesparseconfig.5.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libsuitesparseconfig.5.10.1.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libsuitesparseconfig.5.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libsuitesparseconfig.5.10.1.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libcolamd.2.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libcolamd.2.9.6.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libsuitesparseconfig.5.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libsuitesparseconfig.5.10.1.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libsuitesparseconfig.5.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libsuitesparseconfig.5.10.1.dylib
DEBUG:delocate.libsana:@rpath/libbtf.1.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libbtf.1.2.6.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libsuitesparseconfig.5.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libsuitesparseconfig.5.10.1.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libsuitesparseconfig.5.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libsuitesparseconfig.5.10.1.dylib
DEBUG:delocate.libsana:@rpath/libsuitesparseconfig.5.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libsuitesparseconfig.5.10.1.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libomp.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libomp.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libomp.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libomp.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libomp.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libomp.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libomp.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libomp.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libomp.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libomp.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libomp.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libomp.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libomp.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libomp.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:@rpath/libomp.dylib resolved to: /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libomp.dylib
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
DEBUG:delocate.libsana:Skipped missing dependency /usr/lib/libSystem.B.dylib because it is a system library.
INFO:delocate.delocating:Copying library /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libklu.1.3.8.dylib to finesse/.dylibs/libklu.1.3.8.dylib
INFO:delocate.delocating:Copying library /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libamd.2.4.6.dylib to finesse/.dylibs/libamd.2.4.6.dylib
INFO:delocate.delocating:Copying library /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libcolamd.2.9.6.dylib to finesse/.dylibs/libcolamd.2.9.6.dylib
INFO:delocate.delocating:Copying library /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libbtf.1.2.6.dylib to finesse/.dylibs/libbtf.1.2.6.dylib
INFO:delocate.delocating:Copying library /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libsuitesparseconfig.5.10.1.dylib to finesse/.dylibs/libsuitesparseconfig.5.10.1.dylib
INFO:delocate.delocating:Copying library /Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/libomp.dylib to finesse/.dylibs/libomp.dylib
INFO:delocate.delocating:Modifying install name in finesse/.dylibs/libklu.1.3.8.dylib from @rpath/libamd.2.dylib to @loader_path/libamd.2.4.6.dylib
Fixing: wheelhouse/finesse-3.0a2.dev1110+g852de42c-cp310-cp310-macosx_10_9_x86_64.whl
Traceback (most recent call last):
  File "/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/bin/delocate-wheel", line 8, in <module>
    sys.exit(main())
  File "/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/python3.10/site-packages/delocate/cmd/delocate_wheel.py", line 128, in main
    copied = delocate_wheel(
  File "/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/python3.10/site-packages/delocate/delocating.py", line 643, in delocate_wheel
    copied_libs = delocate_path(
  File "/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/python3.10/site-packages/delocate/delocating.py", line 473, in delocate_path
    return delocate_tree_libs(lib_dict, lib_path, tree_path)
  File "/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/python3.10/site-packages/delocate/delocating.py", line 112, in delocate_tree_libs
    _update_install_names(
  File "/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/python3.10/site-packages/delocate/delocating.py", line 219, in _update_install_names
    set_install_name(requiring, orig_install_name, new_install_name)
  File "/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/python3.10/site-packages/delocate/tools.py", line 136, in modify
    return f(filename, *args, **kwargs)
  File "/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/python3.10/site-packages/delocate/tools.py", line 583, in set_install_name
    replace_signature(filename, "-")
  File "/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/python3.10/site-packages/delocate/tools.py", line 136, in modify
    return f(filename, *args, **kwargs)
  File "/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/python3.10/site-packages/delocate/tools.py", line 955, in replace_signature
    subprocess.run(
  File "/Users/gitlab/builds/v7UZ2U1L/0/finesse/finesse3/envs/finesse/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['codesign', '--force', '--sign', '-', '/private/var/folders/kn/nxysct9107z1wgpvst2rr83r0000gt/T/tmpsm7lut6m/wheel/finesse/.dylibs/libklu.1.3.8.dylib']' returned non-zero exit status 106.
```

**Wheels used**
This zip contains the wheel: [artifacts.zip](https://github.com/matthew-brett/delocate/files/7913836/artifacts.zip)

**Platform (please complete the following information):**
 - OS version: tried both macOS 11 and macOS 10.15
 - Delocate version: 0.10.2

**Comment by SeanDS** [comment]
I don't think so - the path it uses is a temporary CI one. I see you've made an MR that adds printing of the output though, so if that gets put up on pip soon (even as a pre-release) I can update the CI job to use that so I can share what it says.

**Comment by HexDecimal** [comment]
You don't need to wait for a pre-release.  You can tell pip to install from a Git branch directly:
```
pip install git+https://github.com/HexDecimal/delocate.git@refactor-subprocess-calls
```

**Comment by SeanDS** [comment]
True. I just did that and got:

```
    raise RuntimeError(
RuntimeError: Command ['codesign', '--force', '--sign', '-', '/private/var/folders/7j/zd_md_9x0398zxt_p5dzx21r0000gt/T/tmp4fvrrrkp/wheel/finesse/cmatrix.cpython-310-darwin.so'] failed with non-zero exit code 106.
stdout:
stderr:-s is required
```

**Comment by isuruf** [comment]
Is this on a conda environment with `sigtool` installed?

**Comment by SeanDS** [comment]
Yes... sigtool-0.1.2. Is that bad?

**Comment by isuruf** [comment]
Yep. I'll push an update to `sigtool`.

**Comment by SeanDS** [comment]
What's the problem?
I don't actually specify `sigtool` in the conda environment spec, it's getting installed as a dependency by something else (not `delocate`).

**Comment by isuruf** [comment]
https://github.com/thefloweringash/sigtool/pull/9

`sigtool` provides a `codesign` binary that delocate is picking up.

**Comment by SeanDS** [comment]
I see, thanks for the quick fix!

**Comment by HexDecimal** [comment]
Closing as resolved by an update to sigtool.
