### ISSUE TITLE
Incorrect rpath setting in delocate

### ISSUE THREAD

**Issue by larsoner** [matthew-brett/delocate#233]
### Describe the bug

Incorrect `rpath` setting for macos wheel (I think?), see [this CI run](https://github.com/openmeeg/openmeeg/actions/runs/12332998264/job/34421503387?pr=709#step:21:323) which leads to this traceback when trying to import the installed wheel:
```Python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/openmeeg/__init__.py", line 7, in <module>
    from ._openmeeg_wrapper import (
  File "/Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/openmeeg/_openmeeg_wrapper.py", line 12, in <module>
    from . import _openmeeg
ImportError: dlopen(/Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/openmeeg/_openmeeg.cpython-310-darwin.so, 0x0002): Library not loaded: @loader_path/../../../openmeeg.dylibs/libOpenMEEG.1.1.0.dylib
  Referenced from: <745CD5B9-BA1A-3A1A-AC9B-88144A4BFEE8> /Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/openmeeg/_openmeeg.cpython-310-darwin.so
  Reason: tried: '/Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/openmeeg/../../../openmeeg.dylibs/libOpenMEEG.1.1.0.dylib' (no such file)
```
You can see three `../` in the path when there should be one.

### To Reproduce

Some slighty annoying gymnastics are required to get the libraries back into a state that `delocate-wheel` can work with them, but first download the arm64 (macos-15) wheel from the `Artifacts` pane:

https://github.com/openmeeg/openmeeg/actions/runs/12332998264/job/34421503387?pr=709#step:21:323

I was able to reproduce the error on my system with:
```bash
unzip wrapping_macos-15_cmake_OpenBLAS_dynamic_msvc_3.10_latest.zip
# get libraries from "fixed" wheel
unzip openmeeg-2.5.14.dev4-cp310-cp310-macosx_15_0_arm64.whl
mv openmeeg.dylibs dylibs
rm openmeeg-2.5.14.dev4-cp310-cp310-macosx_15_0_arm64.whl
rm -Rf openmeeg-2.5.14.dev4.d*
cd dylibs
ln -s libOpenMEEG.1.1.0.dylib libOpenMEEG.1.dylib
ln -s libOpenMEEGMaths.1.1.0.dylib libOpenMEEGMaths.1.dylib
mv libsz.2.0.1.dylib libsz.2.dylib
ln -s libsz.2.dylib libsz.2.0.1.dylib
cd ..
# do the delocation
mv openmeeg-2.5.14.dev4-cp310-cp310-macosx_11_0_arm64.orig.whl openmeeg-2.5.14.dev4-cp310-cp310-macosx_11_0_arm64.whl
DYLD_LIBRARY_PATH=$PWD/dylibs delocate-wheel -v openmeeg-2.5.14.dev4-cp310-cp310-macosx_11_0_arm64.whl
conda create -n py310 python=3.10
conda deactivate
conda activate py310
pip install ./openmeeg-2.5.14.dev4-cp310-cp310-macosx_15_0_arm64.whl
python -c "import openmeeg"
```
You should see the same traceback as on the CIs:
```Python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/MNE-Python/1.7.0_0/.mne-python/envs/py310/lib/python3.10/site-packages/openmeeg/__init__.py", line 7, in <module>
    from ._openmeeg_wrapper import (
  File "/Applications/MNE-Python/1.7.0_0/.mne-python/envs/py310/lib/python3.10/site-packages/openmeeg/_openmeeg_wrapper.py", line 12, in <module>
    from . import _openmeeg
ImportError: dlopen(/Applications/MNE-Python/1.7.0_0/.mne-python/envs/py310/lib/python3.10/site-packages/openmeeg/_[openmeeg.cpython-310-darwin.so](http://openmeeg.cpython-310-darwin.so/), 0x0002): Library not loaded: @loader_path/../../../openmeeg.dylibs/libOpenMEEG.1.1.0.dylib
  Referenced from: <745CD5B9-BA1A-3A1A-AC9B-88144A4BFEE8> /Applications/MNE-Python/1.7.0_0/.mne-python/envs/py310/lib/python3.10/site-packages/openmeeg/_[openmeeg.cpython-310-darwin.so](http://openmeeg.cpython-310-darwin.so/)
  Reason: tried: '/Applications/MNE-Python/1.7.0_0/.mne-python/envs/py310/lib/python3.10/site-packages/openmeeg/../../../openmeeg.dylibs/libOpenMEEG.1.1.0.dylib' (no such file)
```
And confirm that it's looking three levels up when it should be looking one:
```bash
$ ls /Applications/MNE-Python/1.7.0_0/.mne-python/envs/py310/lib/python3.10/site-packages/openmeeg.dylibs/
libOpenMEEG.1.1.0.dylib		libgfortran.5.dylib		libhdf5.310.5.0.dylib		libopenblasp-r0.3.28.dylib
libOpenMEEGMaths.1.1.0.dylib	libgomp.1.dylib			libmatio.13.dylib		libquadmath.0.dylib
libgcc_s.1.1.dylib		libhdf5.310.3.0.dylib		libopenblasp-r0.3.27.dylib	libsz.2.dylib
```

### Expected behavior

Properly installable wheel.

**Wheels used**
:point_up: 

**Platform (please complete the following information):**
 - OS version: macos-13 Intel and macos-15 arm64 both hit the same problem
 - Delocate version: 0.12.0

**Comment by larsoner** [comment]
... and one last point, I should say that we're doing some gymnastics over in OpenMEEG with SWIG and setuptools and wheel tags in that CI run that I'm not 100% sure we got right, so it's entirely possible that some wheel metadata is wrong or something and that's what messes up `delocate`!

**Comment by HexDecimal** [comment]
I suspect this is related to the existence of this wheels `purelib` directory, which would make this a duplicate of #149

**Comment by HexDecimal** [comment]
Duplicate of #149

**Comment by larsoner** [comment]
Ahh sorry I should have seen that one!
